99designs/aws-vault

aws-vault.go
command/list.go
keyring/keychain_darwin.go
keyring/keyring.go

Adds an `ls` command to list profiles stored in the vault.
```
$ aws-vault ls
default
work
home
```

Add list command

---

aws-vault.go

Set `cli.Ui.ErrorWriter` to `os.Stderr` to that warnings and errors go to stderr not stdout.
[`BasicUi.Error()` from `mitchellh/cli`](https://github.com/mitchellh/cli/blob/8102d0ed5ea2709ade1243798785888175f6e415/ui.go#L109-L117) defaults to using `Writer` if `ErrorWriter` hasn't been set.

Write errors and warnings to stderr, not stdout.

---

vault/profiles.go

Before:
```
$ aws-vault exec env
Profile not found
$ aws-vault exec --profile=foo env >/dev/null
Profile not found
```
After:
```
$ aws-vault exec env
Profile 'default' not found in /Users/pda/.aws/config
$ aws-vault exec --profile=foo env >/dev/null
Profile 'foo' not found in /Users/pda/.aws/config
```
It's not immediately obvious that an entry needs to exist in `~/.aws/config` for each `aws-vault store` credential, so this error should help explain that.
This could also be helped by `aws-vault store` adding a stub entry to the AWS config if one did not already exist.

Error for missing profile reports profile name and config file.

---

aws-vault.go
command/exec.go
command/exec_test.go
command/list.go
command/list_test.go
command/remove.go
command/store.go
command/store_test.go
command/util.go
command/util_test.go
keyring/array.go
keyring/array_test.go
keyring/keychain_darwin.go
keyring/keyring.go
vault/credentials.go
vault/keyring.go
vault/profiles.go
vault/session.go

My aim here was to apply [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) more to the exec command so that it's easier (or possible at all) to test. 
This moves the logic for getting temporary session credentials from AWS into `vault/session.go`, which should in turn be easier to test its self. The keychain session caching moves into a decorator.
Along the way, this also wraps access to the serialized credentials in a decorate on the Keychain that is accessible from the new Profile object.

Refactor sts calls into vault session

---

exec.go
main.go
provider.go

Where previously the session length was fixed at 15 minutes, this extends it to an hour. It also adds a duration flag to `exec`:
```bash
$ aws-vault exec --session-ttl 2h myprofile -- env     
```
Ping @mtibben @pda

Configurable session time, default 8 hours (was 15m)

---

login.go
main.go

This command generates a login link for assumed roles:
```
$ aws-vault login myaccount
https://signin.aws.amazon.com/federation?Action=login....
```

Add a command to generate login links for AWS Console

---

README.md

Adds some documentation about the `mfa_serial` property.
This is important, because if your IAM account has MFA enabled, you need to include your MFA token in its profile configuration in order to make any requests with STS-generated temporary credentials. Otherwise the `AWS_SESSION_TOKEN` will be treated as invalid.

Document MFA configuration

---

keyring/array.go
keyring/array_test.go
keyring/keychain.go
keyring/keychain_test.go
keyring/keyring.go
main.go
provider.go

The keyring package now exposes more of the services it supports (keychain at present), with the following:
```go
type Item struct {
Key         string
Data        []byte
Label       string
Description string
TrustSelf   bool
}
type Keyring interface {
Get(key string) (Item, error)
Set(item Item) error
Remove(key string) error
Keys() ([]string, error)
}
```

Refactor keyring package to allow for rich items

---

config.go
exec.go
keyring/keychain.go
main.go
metadata.go
provider.go

All AWS SDK's check for a [metadata service](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) at http://169.254.169.254, which is used for instance roles. 
This PR runs a server for every exec call and passes it to the subprocess as an `HTTP_PROXY` var and then intercepts the call to the metadata service and returns credentials. This seems to work great and the SDK's know to fetch new credentials when the current ones expire. If one provides a longer underlying session expiry then your role credentials will be renewed without prompting for MFA.
There is a `--write-env` fallback that will also write the env variables like the earlier versions.

Use a local metadata server for credentials, fixes #24

---

provider.go

This makes the MFA token visible while entering. It is not vulnerable to being pulled out of the scrollback buffer as it only lasts for a short duration. 
Both AWS and Google show the MFA token as its being typed.

Show MFA token while typing

---

exec.go

Capture and pass the error from `cmd.Run()` to `ui.Error.Fatal()` so that failed commands are reported and exit with a non-zero status.
Before:
```
$ aws-vault exec 99designs true ; echo $?
0
$ aws-vault exec 99designs false ; echo $?
0
$ aws-vault exec 99designs blargh ; echo $?
0
```
After:
```
$ aws-vault exec 99designs true ; echo $?
0
$ aws-vault exec 99designs false ; echo $?
exit status 1
1
$ aws-vault exec 99designs blargh ; echo $?
exec: "blargh": executable file not found in $PATH
1
```
This needs fine-tuning so that the second case silently passes through the exit status, while the third case still reports that the command wasn't found.  But for now this fixes the much bigger problem of failing to propagate errors at all.

exec: report cmd.Run() error; e.g. command not found.

---

exec.go

This adds a protocol to the `http_proxy` env variable. Verified this fixes the issue for aws-sdk-1.42.0, but having the usual nokogiri issues with getting aws-sdk-1.66.0 installed.

Added protocol to http_proxy, fixes #33

---

Godeps/Godeps.json
login.go

I got sick of copying and pasting or command-clicking the url for `aws-vault login`, so this uses http://github.com/skratchdot/open-golang/open for cross-platform "open in default browser".

Use open-golang to open login url in default browser

---

exec.go
main.go

Sometimes you need to use root credentials (see #15) without an MFA. This flag allows that.

Add a --no-session flag to exec

---

exec.go
main.go
provider.go

Adds a flag (--assume-role-ttl) and support for passing through a custom duration for the assumed role to the VaultProvider.
(Edited to add: this is the first time I've done anything with go - I think I've done this right, and it works for me (TM), but happy to take suggestions on board.)

Add an Assumed Role duration flag.

---

exec.go

The aws CLI needs access to the config file for more than credentials, e.g. setting the default region, or enabling the cloudfront cli preview feature.
This variable was originally nuked in cb5710d. According to @lox's memory:
> I seem to recall the issue is that subshells would try and read the
> aws config file, rather than use the injected credentials and this
> lead to strange combinations of credentials and failures.
While this could cause trouble, it's probably a misconfiguration to have credentials in your config file for profiles managed by aws-vault.
Fixes #65

Don't kill AWS_CONFIG_FILE in forked environment

---

glide.lock
glide.yaml
keyring/array.go
keyring/file.go
keyring/file_test.go
keyring/keychain.go
keyring/keychain_test.go
keyring/keyring.go
main.go

This adds a file backend for storing keyring items encrypted in ~/.awsvault/keys/{keyname}. Keys are encrypted as JWT tokens.
The usecase for this is for command-line linux usage. It also opens up the possibility of using it on servers to store credentials.

Add a basic file backend

---

login.go
main.go

New flag for login: `aws-vault login --stdout xxx`: prints the login URL to stdout instead of opening in default browser.

Stdout parameter to not open login URL in default browser

---

main.go

Broken by https://github.com/99designs/aws-vault/pull/74
With `Enum` (return the value) rather than `EnumVar` (write to var), `PromptDriver` never gets set, causing this error:
```
panic: Prompt method "" doesn't exist
goroutine 1 [running]:
panic(0x44bcb00, 0xc82000fcf0)
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/99designs/aws-vault/prompt.Method(0x0, 0x0, 0xc8200e1450)
/Users/pda/code/go/src/github.com/99designs/aws-vault/prompt/prompt.go:22 +0x1b1
main.configureLoginCommand.func1(0xc820082cf0, 0x0, 0x0)
/Users/pda/code/go/src/github.com/99designs/aws-vault/main.go:185 +0x5e
github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc8200c4498, 0xc820082cf0, 0x0, 0x0) …
```

prompt flag writes to globals.PromptDriver

---

README.md

I added a formula for `aws-vault` to homebrew cask in https://github.com/caskroom/homebrew-cask/pull/23637. I _propose_ that the README should talk about that as an installation method since many folks just aren't used to or comfortable with manually dropping binaries in place, setting permissions correctly, etc.
I'm not wedded to this at all, though, so feel free to close if you disagree :smile:

Add `brew cask` install instructions for macOS

---

keyring/keychain.go

These lines were causing `serviceRef` to be released twice. It looks like some copy/paste shenanigans from the blocks just above where I've made these changes, e.g. [keychain.go:59](https://github.com/99designs/aws-vault/blob/42854c4d7d2af53a0978244ee20db25038312989/keyring/keychain.go#L59). I think it's pretty safe to assume from the context that these lines were meant to release `accountRef` not `serviceRef`.
These were causing a crash on macOS 10.12 beta that looked like:
```
SIGTRAP: trace trap
PC=0x7fff86a8b985 m=5
signal arrived during cgo execution
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x442a000, 0xc8200dfe20, 0xc800000000)
/usr/local/Cellar/go/1.5.3/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc8200dfdf0 sp=0xc8200dfdc0 …
```

Fix crashes in keychain Get & Remove

---

Makefile
README.md

This leads to broken binaries if codesigning is used after building with golang 1.6 or 1.7.

Makefile check doesn't handle golang 1.6 and 1.7

---

keyring/keychain.go
keyring/keychain_test.go

This reverts #85, because it turns out to not actually work under macOS Sierra. 
This change uses the `SecKeychainGetStatus` to see if the keychain exists. I suspect we might also need to drop extensions from paths.

Check keychain exists with SecKeychainGetStatus

---

Makefile

This changes the `make release` target to build cross-compiled binaries for darwin, linux and win32. 
I thought this might be nice for people not on OSX.

Updates Makefile to generate darwin, linux and win32 bins

---

provider.go

Allows a user to add a `role_session_name` to their `~/.aws/config` file, which will be used in place of the Unix timestamp if available.

accept role_session_name from ~/.aws/config

---

provider.go

Otherwise build fails on Go 1.6.2 with this error:
```
provider.go:224: roleSessionName declared and not used
```

provider.go assumeRole: reassign, not redeclare, roleSessionName

---

exec.go
login.go
main.go
provider.go

Based on feedback in this [aws forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=742905&#742905), it became obvious that the new longer federated session expiry could be used if IAM credentials were used to assume the role, vs our standard iam -> session token -> assume role -> federation tokens. 
I'm not sure why I never realized that the session token step was unneeded. I suspect it was because it adds complexity to the code, as you need to conditionally apply MFA to the AssumeRole call if there isn't a session with MFA already applied to it.
Regardless, this works, although I've been drinking a lot of wine, so I might be imagining it all.

Use iam credentials for login, allowing session expiry of 12h

---

Makefile
add_test.go
config.go
keyring/file.go
keyring/keychain.go
keyring/kwallet.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/github.com/mitchellh/go-homedir/homedir_test.go

This was mostly due to `user.Current()` requiring cgo code that fails in cross-compiled binaries. This PR uses an external library for getting the users home dir that works in a cross-compiled environment.

Issue #93 pointed out that cross-compiled binaries fail under linux

---

add.go
rm.go

```
$ aws-vault rm --sessions-only redacted
Deleted 11 sessions.💀
```
The skull (if it renders properly here) is my shell saying there was no newline at the end of the command output.  `log.Println` and `log.Printf` seem to be used elsewhere, but `fmt.Printf` was used here; fixed.

add.go, rm.go: use log.Printf vs fmt.Printf to ensure newline.

---

login.go

Previously, the login destination was https://console.aws.amazon.com/console/home. This meant that even if you had a specific region set in your `~/.aws/config` for the profile, it would use the last region you were in. Hilarity ensues.

Login to the correct region based on profile config

---

login.go

Show a useful error rather than "400 Bad Request"

Show error when using a profile without source_profile

---

exec.go

Code was already there but the order of if blocks made this block
unreachable.
Demo:
```
$ ~/go3d/bin/aws-vault exec mykey -- bash -c 'exit 2'
$ echo $?
2
$ /usr/local/bin/aws-vault exec mykey -- bash -c 'exit 2'
aws-vault: error: exit status 2
$ echo $?
0
```

exec: Exit with exit code of subcommand

---

keyring/file.go

Fix for #112 
The file descriptor passed to `terminal.ReadPassword` is hardcoded to `1` which works fine for UNIX systems but is not correct for a Windows environment. Setting this to the actual file descriptor of stdout fixes the problem.
```
C:\Users\shorty>aws-vault add test
Enter Access Key ID: AKIAAAAAAAAAAAAAAAAAAAAA
Enter Secret Access Key: zzzzzzzzzzzzzzzzzzzzzzz
Enter passphrase to unlock C:\Users\shorty\.awsvault\keys:
Added credentials to profile "test" in vault
```
Also fixed nearby code that did nothing with error values.

Fix terminal input in windows

---

vendor/github.com/dvsekhvalnov/jose2go/README.md
vendor/github.com/dvsekhvalnov/jose2go/ecdh.go
vendor/github.com/dvsekhvalnov/jose2go/jose.go
vendor/vendor.json

Update the jose2go dep based on http://blogs.adobe.com/security/2017/03/critical-vulnerability-uncovered-in-json-encryption.html
Not sure if Elliptic Curve cryptography is actually used, but better safe than sorry.
```shell
go get -u github.com/dvsekhvalnov/jose2go
govendor update github.com/dvsekhvalnov/jose2go
```

Update jose2go dep

---

alias_darwin.go
alias_linux.go
alias_windows.go
server.go

Hello!
This PR makes `exec`'s server mode compatible with linux. The syntax for the alias installation is different on this platform.
To do so, I extracted the `installNetworkAlias` function in platform specific files. I also added an explicit error message on windows.
Best,

Support linux for exec --server

---

config.go
exec.go
login.go
main.go

Primarily:
```bash
aws-vault login llamas
aws-vault: error: No credentials found for profile llamas.
Use 'aws-vault add llamas' to set up credentials or 'aws-vault list' to see what credentials exist
```
/cc @toolmantim

Adds some better error messages

---

Makefile

When building windows binary as part of `make release`, add `.exe` file extension so Windows considers the file executable and users know that it's not e.g. a zip file.

Makefile: windows build has .exe file extension.

---

main.go

I used aws-vault heavily with Terraform. Some operations (especially RDS-related) can take in excess of 15m to execute. It would be useful to be able to set this as an environment variable rather than remember to pass it as a flag for each run.

Add configurable ENV support for assume-role-ttl

---

keyring/keychain.go
vendor/github.com/keybase/go-keychain/LICENSE
vendor/github.com/keybase/go-keychain/README.md
vendor/github.com/keybase/go-keychain/corefoundation.go
vendor/github.com/keybase/go-keychain/ios.go
vendor/github.com/keybase/go-keychain/keychain.go
vendor/github.com/keybase/go-keychain/macos.go
vendor/github.com/keybase/go-keychain/util.go
vendor/vendor.json

I've been meaning to do this for ages, but finally got around to putting in the PR's to https://github.com/keybase/go-keychain that will let us entirely replace our long-ago-forked custom keychain interaction code. So much joy in this diff.
https://github.com/keybase/go-keychain/pull/12
https://github.com/keybase/go-keychain/pull/13

Replace keychain with go keychain

---

config.go
keyring/keychain.go
keyring/keychain_test.go
provider.go
sessions.go
vendor/vendor.json

I noticed that we were back to displaying three prompts for every access, even when there is a session. Should only prompt once now and not at all if there is an active session.

Fixed regression that prompted for keychain access for sessions

---

keyring/keychain.go
keyring/keychain_test.go

Another regression from the go-keychain stuff. Set needs to delete any existing keys before setting them, as a duplicate returns an error in Keychain.

Keychain doesn't overwrite, needs delete on duplicate

---

provider.go
rotate.go

Based on #132 and #133, key rotation was broken in a number of ways:
* It used a session, which means IAM calls are only possible if there is an MFA
* It didn't support profiles, so if your master creds didn't have permission to do IAM stuff and you needed to assume a role to do so it wouldn't work
* It dumped your creds to the console on error
This fixes all of the above as well as reducing the amount of prompts you get from Keychain. 
Damn you for nerd sniping me just before I fell asleep @pda.

Support profiles in rotate

---

provider.go

Previously we used `NewChainCredentials` to try in order the AWS env vars, then `~/.aws/credentials` and then finally our vault provider. The idea was if you started out with old school credentials it would kind of work. It was a bad idea, and the end result is that errors from our vault provider show up as "No credentials found" rather than useful errors. This has (in part) led to #49 by masking the underlying errors.

Drop support for the env and shared credentials provider

---

exec.go

Minor adjustment to `aws-vault --debug exec ...` logging, because when I saw "Writing temporary credentials ..." I was briefly alarmed.
This PR:
* refers to setting environment, rather than writing environment.
* logs more specifically about environment vars being set.
```
$ aws-vault --debug exec example
2017/08/25 15:42:32 Parsing config file /Users/pda/.aws/config
2017/08/25 15:42:32 Looking up keyring for example
2017/08/25 15:42:41 Using session ****************LDNB, expires in 3h52m34.384573005s
2017/08/25 15:42:41 Parsing config file /Users/pda/.aws/config
2017/08/25 15:42:41 setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2017/08/25 15:42:41 setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2017/08/25 15:42:41 setting subprocess env: …
```

exec debug logging: more specific messages, and s/write/set/.

---

vault/config.go
vault/provider.go
vault/sessions.go

When a session is requested from the keychain, the master credentials shouldn't be requested. Instead we should be prompting for access to the session keychain item.
The net effect is the same, requesting master credentials pops a prompt, and then the next time you request access to a session it pops a prompt, but it's the correct prompt, for the correct item, the session. 
I guess the downside of this, and it's probably a sizeable downside is that you can't hit "Always trust" the second time and never see a prompt again. You might be able to do that for the master credentials, but you would need to do it for every new session key that is stored.
Bug, feature, regression, improvement, not sure. Maybe all?

Refactor order in which access to keychain is requested

---

cli/login.go
cli/rotate.go

It seems `User.UserName` isn't always present in a [`GetUser`](http://docs.aws.amazon.com/IAM/latest/APIReference/API_GetUser.html) response. I experienced this while using aws-vault with root credentials
So this now falls back to parsing the `User.Arn`.
Fixes https://github.com/99designs/aws-vault/issues/114

Fallback to Arn when Username doesn't exist

---

cli/exec.go
cli/exec_test.go

We try to read cmd.Process in the thread that handles incoming
signals, but there's no synchronization between that goroutine and the
one that sets cmd.Process to a non-nil value.
This might be overkill, e.g. there may be a way to write this with
less code, but I confirmed that this patch addresses the
race when shutting down the program.
Fixes #158.

Fix data race

---

vault/provider.go

Currently we rely on the default region finding behaviour in the aws client. I have a theory that this causes some issues sometimes, so this explicitly sets a region if one is specified in the aws config.

Read the region from the config for sts calls

---

cli/exec.go

app.Error merely logs, instead of quitting the program with a non-zero
return code. This means some subset of programs fail to exec the
underlying binary and then exit 0, which might incorrectly indicate to
a caller (like me) that they exited successfully.
Fixes #167.

Use app.Fatal instead of app.Error

---

cli/add.go
cli/add_test.go
vault/config.go
vault/config_test.go

This adds a profile (if one doesn't exist) to `~/.aws/config` when you add a profile with `aws-vault add`. 
This helps keep your config aligned with your credentials in your keychain.

Add entry to aws config file in add command

---

README.md
cli/rotate.go
vault/rotator.go

Key rotations is complicated and there are lots of edge cases, this adds some documentation on what IAM permissions are required, along with making some of the AWS error messages clearer (use a username when one exists, rather than relying on a null user).
Closes #178.

Add docs for rotate and clearer errors

---

server/server.go

Resolves #184 - the Go AWS SDK can now hit the instance-id endpoint when testing for the availability of the metadata endpoint.

spoof an instance ID so we can pass the go aws-sdk Available() call

---

server/alias_windows.go
server/server.go

Issue https://github.com/99designs/aws-vault/issues/166 describes whats going on here
This is a breaking change for the way the metadata server is started
```sh
aws-vault exec <environment> --server
```
is now
```sh
aws-vault exec <environment> -s -- aws-vault server
```

Metadata server running on windows

---

cli/add_test.go
cli/global.go
vault/sessions.go
vendor/github.com/99designs/keyring/README.md
vendor/github.com/99designs/keyring/config.go
vendor/github.com/99designs/keyring/file.go
vendor/github.com/99designs/keyring/keychain.go
vendor/github.com/99designs/keyring/keyring.go
vendor/github.com/99designs/keyring/kwallet.go
vendor/github.com/99designs/keyring/libsecret.go
vendor/github.com/99designs/keyring/prompt.go
vendor/github.com/keybase/go-keychain/macos.go
vendor/vendor.json

This updates to the latest https://github.com/99designs/keyring API, which is a fairly major change. I've checked that we are setting the correct defaults so that it's backwards compatible on everything but kwallet and libsecret, but have eyeballed them.
Closes #188.

Bump keyring version

---

cli/global.go
cli/ls.go
vault/provider.go
vault/sessions.go

This can be merged after #197.
It adds the expiry time for a session into the item description that is stored unencrypted. This means we can skip expired sessions and avoid lots of prompts.
Closes #188 (hopefully).

Add expiry data to session

---

cli/global.go

This supersedes #144. It allows for a specific macOS keychain to be used, which means that either the default/ login keychain can be used rather than the previous `aws-vault.keychain` that was created. 
The default remains `aws-vault`, so it's backwards compatible.

Allow for different macOS Keychain to be used

---

server/server.go

Via #198 we were made aware that it was possible to route traffic to `169.254.169.254:80` even if it is aliased to `lo0`. This means anyone on the same network segment could access the credential server whilst an `aws-vault exec --server blah` command was running. 
This adds a check for a `RemoteAddr` of `127.0.0.1`. I don't love this approach, would much prefer something lower down, but it seems like a pragmatic mitigation in the short term. Any thoughts @mtibben @clintoncampbell?

Prevent local network segment from accessing credential server

---

cli/global.go

This fixes a regression from v4.1.0 to v4.2.0, where collection
was renamed to 'aws-vault'
This is caused by that github.com/99designs/keyring previously
used the collection name 'awsvault' by default.
This was changed in commit 5a0d04e 'Add backend specific config'.

Make secret-service use collection 'awsvault'

---

cli/exec.go

KingPin can provide dynamic values to it's bash-completion with the HintAction() API
https://github.com/alecthomas/kingpin#additional-api
Using this, you can have auto-completion on the profile names in ~/.aws/config when running:
```
aws-vault exec <tab>
```
You can see what will be fed to bash autocompletion with:
```
aws-vault --completion-bash exec
```
I tried to add a test in exec_test.go, but ran into trouble trying to generate a test config like in config_test.go. Some help here would be appreciated.

Add a HintAction to exec to let KingPin autocomplete profile names.

---

cli/exec.go

aws-vault captures SIGINT in order to forward it to the spawned process.
Since the signal capturing is set up way before the child process is
spawned, in particular before getting the credentials, the signals are
captured at the mfa device prompt making it impossible to exit the CLI
using Ctrl-C at that point.
This moves the signal set up closer to when the child process is spawned,
making it possible to exit using Ctrl-C at the mfa prompt.
Tested on linux/KDE/kdewallet backend

Move the signal setup closer to cmd.Start()

---

vault/provider.go

Now allowed
https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/

Increase MaxAssumeRoleDuration to 12 hours

---

.travis.yml
vendor/github.com/keybase/go-keychain/corefoundation_1.10.go
vendor/vendor.json

Previously compiling aws-vault on Go 1.11 beta 2 would fail with a
compilation error. For more information see:
https://github.com/golang/go/commit/94076feef
https://github.com/golang/go/issues/26721
https://github.com/keybase/go-keychain/pull/30
Also, add tip to the Travis CI build matrix. And run tests on the latest point
release for Go 1.8, 1.9, and 1.10, so 1.10.3 instead of 1.10 for example.

Update go-keychain to resolve Go 1.11 compilation issue

---

vault/config.go
vault/provider.go

A quick fix to support the [external_id option](https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html#cli-roles-xaccount) in profile config.
Have tested this against one of my own roles.

Read external_id into Profile and pass to assume role requests

---

vault/rotator.go

This addresses: https://github.com/99designs/aws-vault/issues/182
```
✔ ~/work/go/src/github.com/99designs/aws-vault [bugfix/rotate-with-mfa|✔]
14:34 $ aws-vault rotate -t $(mfa otp devtestnate)  devtestnate
Rotating credentials for profile "devtestnate" (takes 10-20 seconds)
aws-vault: error: Failed to get credentials for devtestnate: AccessDenied: User: arn:aws:iam::1234567890:user/devtestnate is not authorized to perform: iam:CreateAccessKey on resource: user devtestnate
status code: 403, request id: a74b63f9-6f51-11e8-945c-5308d718cb58
```
I spend some time trying to figure out why `NoSession` was hardcoded to `true` but couldn't figure it out.  As far as I can tell, I need to use a session in order to use MFA.  It's more secure to restrict CreateAccessKey to those with MFA present. …

Always use a session to rotate AWS keys

---

USAGE.md

This PR documents the environment variables that can be used to override `aws-vault`'s defaults.

Mention environment variables in USAGE.md

---

cli/server.go

Some notes:
> The "proxy" server starts up in the background and binds to 169.254.169.254:80, which is what the aws tooling connects to. It needs root permissions to create the iface and bind to a port < 1024. This is what is triggered by aws-vault server. It's meant to be pretty useless on it's own, and simply proxies requests to localhost:9099 if it exists.
> 
> The "credential" server is started at the beginning of an aws-vault exec --server invocation and it only runs for the duration of that command. It's the one with the keys to the kingdom, so it binds to localhost:9099.
https://github.com/99designs/aws-vault/pull/174#issuecomment-340921440
Closes #207.

Remove server subcommand from `--help`

---

cli/login.go
vault/provider.go

This is a feature enhance to #278 by @maishsk. Thanks a lot for the idea. I tested this both in commercial and gov-cloud region and seems to work like a charm. This also takes cares of the region issue as per #285 .

Add service option initially implemented by @maishsk

---

vault/config.go

I had a stray `$AWS_CONFIG_FILE` variable in my environment and didn't understand why `aws-vault` refused to work well. This just adds a log line to highlight what is going on

Add debug statement if using AWS_CONFIG_FILE

---

README.md
cli/global.go
vendor/github.com/99designs/keyring/README.md
vendor/github.com/99designs/keyring/config.go
vendor/github.com/99designs/keyring/keychain.go
vendor/github.com/99designs/keyring/keyring.go
vendor/github.com/99designs/keyring/pass.go
vendor/vendor.json

Given the pass backend for keyring is ready (https://github.com/99designs/keyring/pull/33), this adds command line options and variables for its configuration.
`--pass-dir` and `AWS_VAULT_PASS_DIR`
`--pass-cmd` and `AWS_VAULT_PASS_CMD`
`--pass-prefix` and `AWS_VAULT_PASS_PREFIX`

Add keyring pass backend options

---

USAGE.md
cli/exec.go

Enhances #299 
Signed-off-by: Noel Georgi <git@frezbo.com>

Adding credential helper

---

vendor/github.com/99designs/keyring/pass.go
vendor/vendor.json

Update govendor with resolution to issue https://github.com/99designs/aws-vault/issues/321 where the pass backend was being selecting instead of file, and then failing because the pass executable was not available. 
See: https://github.com/99designs/keyring/pull/34.

Update govendor - Ensure passcmd is on the callers PATH

---

cli/global.go
vault/provider.go
vault/sessions.go

Address #219 as follow up to 99designs/keyring#16
Default to trusting sessions, but not root credentials. This reduces the need to re-enter password and click "Allow" (or "Always Allow").
Users would not be prompted for passwords for session access/modification, but they would still need to be prompted when the root credentials were accessed. This change in behavior is likely welcome by all, but might warrant a release note in the next release.

 Default to trusting sessions, but not root credentials to address #219

---

USAGE.md

Tiny tweak:
```diff
-If you want to remove sessions … do this with the `--session-only` flag.
+If you want to remove sessions … do this with the `--sessions-only` flag.
```
From the code, the canonical form of this option is `--sessions-only` (_plural_).
**NB** I can open an issue for this if you like; let me know if I should.

Fix typo in USAGE document

---

README.md
USAGE.md
cli/login.go
vault/provider.go
vault/rotator.go

- mfa token only needs to be provided once per source rather than once
per profile by adding `mfa_serial = <arn>` to the root source profile
- allows assume role chains (e.g. roleB <- roleA <- master)
resolves #329 
resolved #310

retrive session credentials recurisvely

---

cli/login.go

fix for GetFederationToken with usernames over 32 characters
Fixes #350

Truncate username for GetFederationToken

---

.gitignore
USAGE.md
cli/login.go

- `--assume-role-ttl` on exec honored the environment variable `AWS_ASSUME_ROLE_TTL`. This has been fixed for login command
- `--profile` on exec has a hint if not passed in, added this to login command

Fix login flag behavior to match that of identical flags on exec

---

cli/login.go
vault/provider.go

- detect profile cycles in NewVaultCredentials
- use NewVaultCredentials in `aws-vault login`
fixes #381

thread any found MFASerial value through recurive Retrieve calls

---

README.md

- There's now a formula for `aws-vault` in Homebrew on Linux
(https://github.com/Linuxbrew/homebrew-extra/blob/master/Formula/aws-vault.rb),
because Casks don't work on Linux. This change shows that users can
`brew tap linuxbrew/extra` and `brew install aws-vault`, or `brew
install linuxbrew/extra/aws-vault` (the documentation I've gone with).

Document that aws-vault is available via Homebrew on Linux

---

cli/exec.go

This addition allows you to override MFA from the exec command. This would be useful for times when you want change between MFA serials without modifying your `.aws/config` file. It would also help with being able to set a forced override of MFA serial with an environment variable.
How to test:
1. `AWS_MFA_SERIAL=some:fake:arn aws-vault exec my-profile -- ls`
2. `aws-vault exec --mfa-serial-override=arn:aws:iam::<aws-acct-id>:mfa/fake my-profile`

Added MFA Override option

---

USAGE.md

When I use aws-vault + terraform with multiple profiles, the MFA doesn't prompt and terraform plan fail. It takes times to find out the solution, so I would like to add detail to the document.

Added documentation of credential-process with prompt

---

completions/fish/aws-vault.fish

Currently there is fish completion for bash and zsh.
Add fish completion, which uses `aws-vault --help` to complete the first argument; and then looks at AWS config to complete subsequent ones with IAM roles.
I've been using this for a while successfully.

Add fish completion

---

cli/exec.go
cli/login.go
vault/provider.go

This flag allows you to use short lived sessions without saving them
to your keyring.
This is useful (at least) for the password store backend to not save
the history of all sessions in the password store's git repository.
This fixes #418

Add --no-save-session option for exec/login

---

USAGE.md

This PR adds some documentation on how to configure a yubikey as a virtual MFA device. 
I believe an integration like #392 is preferable for #230 but this is another way to solve this issue.

Added how to configure aws-vault as a virtual MFA device

---

go.mod
go.sum

There have been several session-based bugfixes since 0.20.17 that should
be part of aws-sdk now.
Some notable examples include:
https://github.com/aws/aws-sdk-go/releases/tag/v1.21.0
https://github.com/aws/aws-sdk-go/releases/tag/v1.22.0
https://github.com/aws/aws-sdk-go/releases/tag/v1.23.6

Upgrade AWS SDK to latest version

---

main.go

This fixes an issue where piping the standard output from `aws-vault exec` to another program hides error messages when `aws-vault` itself encounters an error.  For example, when an MFA token is invalid.
Thanks for making such a useful tool!

Report errors via stderr

---

go.mod
go.sum

[Ignore deprecation warnings](https://github.com/keybase/go-keychain/pull/55) in cgo to allow aws-vault to compile on macOS Catalina

Get aws-vault compiling on macOS Catalina

---

Makefile
bin/create-dmg

Adds a macOS packaging script to sign the binary, create a dmg and notorize the dmg.
Fixes #430

Create notorized dmg for macOS releases

---

bin/create-dmg

Harden the runtime and add a secure timestamp (as [required by Catalina in January 2020](https://developer.apple.com/news/?id=09032019a)). Also sign the DMG

Sign dmg, harden runtime

---

cli/ls.go
vault/provider.go
vault/sessions.go
vault/sessions_test.go

If the master credentials were used as the source for:
- role A without mfa_serial
- role B with mfa_serial
Then, creating a cached session with role A would result in operations
with role B failing because the temporary session established when
assuming role A would not have been created with an mfa token.
The mfa serial is now encoded in the cache key, so that the scenario
mentioned above produces distinct cache keys - one with an mfa serial
and one without an mfa serial.
This also resolves a potentially unexpected behavior when a user changes
the value of a mfa_serial attribute.
Because the session key format has changed, any sessions matching the
previous pattern will be identified as obsolete and removed, similarly
to how expired sessions are removed as they are visited.
fixes #438 …

fix: session cache key should vary with mfa serial

---

USAGE.md
cli/exec.go
cli/login.go
cli/rotate.go
vault/rotator.go

Rotate didn't respect the AWS_MFA_SERIAL environment variable that is
used by the AWS SDK. when mfa_serial is defined in the profile directly,
or even 1 level of source_profile contains mfa_serial it made use of
that.
If however the mfa serial was provided as an environment variable with
AWS_MFA_SERIAL the rotate command failed.
This change allows rotate to pick up AWS_MFA_SERIAL env var and use a session
when the env var is defined.

Add support for AWS_MFA_SERIAL env var for rotate

---

cli/add.go
cli/exec.go
cli/global.go
cli/login.go
cli/ls.go
cli/rm.go
cli/rotate.go
vault/getuser.go
vault/provider.go
vault/rotator.go

Refactors variable names to improve clarity of intent.
There are many instances of "profile" being used in the source code. I've changed these variable names to be either `profileName` (the name of an ordinary profile) or `credentialName` the name of a credential (corresponding to a profile)
This makes the code easier to work with as you know whether the variable is referring to a credential or a profile. This naming scheme is identical to what you see when using `aws-vault list`.
This is a pure refactor and doesn't change any behaviour

Refactor variable names

---

USAGE.md
cli/add.go
cli/exec.go
cli/exec_test.go
cli/global.go
cli/login.go
cli/ls.go
cli/rm.go
cli/rotate.go
server/server.go
vault/config.go
vault/config_test.go
vault/getuser.go
vault/keyring.go
vault/provider.go
vault/rotator.go
vault/sessions.go

Fixes #448.
#445 removed the profile chaining behaviour for `mfa_device`, as it broke compatibility.
This PR introduces a `parent_profile` parameter to specify wanted inheritance behaviour. This gives users the ability to build up more complex configurations without the need for templating.
Using `parent_profile` allows a profile to import all of the config and credentials from the specified parent profile. This includes `mfa_serial` but also extends to other config options. `source_profile` retains its original semantics of importing credentials only, which means compatibility with aws cli and the SDK.
It should be noted that aws-cli and the AWS SDK does not recognise `parent_profile` as a variable and will be ignored
In order to achieve this, I needed to refactor parts of the codebase …

Add parent_profile config variable

---

cli/exec.go
cli/exec_default.go
cli/exec_unix.go

In order to pass through signals to the new process, a real exec syscall should be done.
I think this should fix #453

Do a real exec on execution

---

cli/exec.go

makes it obvious to new users that exec defaults to running the shell as a subprocess.

exec --help describe default command

---

vault/config.go
vault/config_test.go

This PR simply allows for the user to specify upper or lower (or mixed case) section and key names in their config. I raise it as I wasted 3 hours of my life wondering why my aws-vault generated session was invalid before realising mfa_**S**erial=arn:aws:iam::... was not being read.
The aws cli also ignores case. I've proven this by running 'aws configure' then 'aws_access_key_id=AK...' to '**A**ws_access_key_id=AK...' and it still reads the credentials. 
I've modified the test for config to handle this use-case.
There is another related issue to address: a user specifying a token value, but not an MFA serial, is returned an invalid session rather than being warned that there's no point specifying token value if serial isn't supplied. I'll try and get a PR out to handle that.

Ignore case of section and key names when parsing config.

---

USAGE.md
cli/exec.go
cli/login.go
vault/config.go
vault/config_test.go
vault/tempcreds.go

1. Replaces the `--session-ttl`, `--assume-role-ttl` and `--federation-token-ttl` flags with a single `--duration` flag.
Given that we know which credential call will be made, having 3 flags is more complex than is necessary. This is especially apparent on the login command, where all 3 flags could potentially be used in creating the session, and it's difficult to know which flag to use.
The `AWS_SESSION_TOKEN_TTL`, `AWS_ASSUME_ROLE_TTL`, `AWS_FEDERATION_TOKEN_TTL` env vars remain available for users who require more fine-grained control over the session.
2. Changes the default durations 
- `GetSessionToken`: 1h (or 8h when using AssumeRole and the session is primarily to cache MFA) (previously 4h)
- `AssumeRole`: 1h (previously 15m)
- `GetFederationToken`: 1h (previously 12h)
Rationale: …

Update session duration defaults and the CLI flags

---

README.md
USAGE.md

We have faced an issue with that change explains and we think is a good point to share it.
We had a machine that for some reason had the environment variables previously set and after run the `aws-vault`in server mode we cannot run any aws command without the `aws-vault`first.

Add more --server instructions

---

vault/config.go
vault/config_test.go

Fixes issue #475 by configuring the INI lib to output the default header. Some other tools that read the AWS config file bork when this header is missing, despite it being valid for the INI specification. To be most compatible with other tools, any tool that edits/rewrites these files should use the same format as the stock AWS CLI tools -- and thus have the default header.

475 5.0 removes default block header

---

Makefile

It has come to my attention that aws-vault is missing binaries for Linux AMD64. Apologies to @QuinnyPig for this shameful oversight
[![image](https://user-images.githubusercontent.com/980499/71979339-93c3d700-3271-11ea-9c88-47c9f97d29b5.png)](https://twitter.com/QuinnyPig/status/1214665344431738881)

Build binaries for Linux ARM64

---

USAGE.md

Updates some out of date documentation in `USAGE.md` since [v5.0.0](https://github.com/99designs/aws-vault/releases/tag/v5.0.0).
See #464
There are a lot of option combinations here I haven't tried, so if anything else in here needs to change please lmk - this is my first PR to this project 😄

Update USAGE doc for duration flag change since v5.0.0

---

cli/exec.go
cli/login.go
cli/rotate.go
vault/config.go
vault/vault.go

Fixes the regression to `--no-session` that occurred in v5.0.0. 
Using `--no-session` now again correctly disables use of `GetSessionToken`
Fixes #488 and #493

Fix --no-session

---

USAGE.md

Hi!
I was just trying out this `parent_profile` feature and found the example was incorrect.
```
aws-vault: error: exec: Failed to get credentials for <REDACTED>: InvalidParameter: 1 validation error(s) found.
- minimum field value of 900, AssumeRoleInput.DurationSeconds.
```

[doc] Use valid duration_seconds value

---

go.mod
go.sum

Fixes #513 
1c0b58a22cec8ef04f01a20ef861787d72a18bed from #481 released in [v5.1.0](https://github.com/99designs/aws-vault/releases/tag/v5.1.0), as part of a substantial overhaul, introduced a `keyring.Has(key)` check where previously it just hoped for the best and the aws-sdk ended up attempting to `Keyring.Get(key)` as part of the credential provider. In the `secret-service` backend (linux / libsecret / gnome keyring), `Get` was unlocking the item as needed, but `Has` was not unlocking the items/collection; instead it would return empty strings for a locked collection.
https://github.com/99designs/keyring/pull/61 fixes the upstream `Keyring.Has()` bug, and this patch brings the resulting [v1.1.4 release](https://github.com/99designs/keyring/releases/tag/v1.1.4) into aws-vault.
This …

99designs/keyring v1.1.4; fix linux / secret-service bug

---

prompt/kdialog.go

This allows to use [KDialog](https://kde.org/applications/utilities/org.kde.kdialog) as prompt.

Add support for kdialog

---

vault/config.go

AWS_FEDERATION_TOKEN_TTL env var currently populates `NonChainedGetSessionTokenDuration` configuration, thus STS tokens for non-roles use the default duration of 1h.
Closes #550

Link AWS_FEDERATION_TOKEN_TTL to correct Config field

---

README.md

The example output was missing AWS_DEFAULT_REGION and AWS_SESSION_EXPIRATION

README: Add missing AWS_ environment variables

---

cli/exec.go
cli/server.go
server/proxy_default.go
server/proxy_unix.go
server/server.go

Refactors the exec and server code to make it more consistent and easier to modify.
The motivation was that the change at #542 was a lot more difficult than it needed to be. This should also make it easier to land the ECS server PRs #400 #375
The proxy process is now completely cut back to being a http proxy only, as it originally was. That means `sudo aws-vault server` is executing the smallest amount of code necessary

Improvements to exec and server

---

cli/exec.go
cli/server.go
server/ec2.go
server/ec2alias_bsd.go
server/ec2alias_linux.go
server/ec2alias_windows.go
server/ec2proxy_default.go
server/ec2proxy_unix.go
server/ecs.go
server/httplog.go

Rebases #375
AWS SDKs universally support the ECS Credential Service, which supports
reading the service URI from environment variables.
Providing an http interface allows the subprocess to refresh credentials
as long as the master credentials session is valid.
Supporting the ECS Credential provider offers the following advantages
over the EC2 Metadata provider:
- Binding to a random, ephimeral port
- Does not require adminstrator privileges
- Allows multiple providers simultaneously for discrete processes
- Partially mitigates the security issues that accompany the EC2
Metadata Service because the address is not well-known
- Requiring an Authorization token further mitigates the potential for
another process to access the credentials, since the Authorization
token is only exposed to the …

Add ECS server

---

cli/exec.go
cli/login.go

Adds a `--region` override flag to login and exec
Fixes #531

Add --region to login and exec

---

USAGE.md
prompt/kdialog.go
prompt/osascript.go
prompt/prompt.go
prompt/terminal.go
prompt/ykman.go
prompt/zenity.go
vault/vault.go

Support for Yubikey OATH-TOTP via ykman.
Thanks to @j0hnsmith for the initial PRs at #316, #514, #533
Could someone with a Yubikey please test this? @j0hnsmith @jtopper or anyone else? 
[Docs](https://github.com/99designs/aws-vault/blob/ykman-support/USAGE.md#using-a-yubikey) and [binaries](https://github.com/99designs/aws-vault/releases/tag/v5.5.0-alpha2)

Yubikey support

---

USAGE.md
contrib/enable-mfa-device-ykman.sh

This script helps to add a yubikey using ykman. See https://github.com/99designs/aws-vault/pull/558

Add contrib script to enable a mfa device via ykman

---

README.md
USAGE.md
cli/login.go
vault/config.go
vault/ssorolecredentialsprovider.go
vault/vault.go

This PR hopefully closes #449 by adding support for AWS SSO.
Given a [AWS SSO Profile configuration](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html) in `~/.aws/confg`:
```ini
[profile Administrator-123456789012]
sso_start_url=https://aws-sso-portal.awsapps.com/start
sso_region=eu-west-1
sso_account_id=123456789012
sso_role_name=Administrator
```
This PR allows `aws-vault` to obtain short lived credentials for an SSO profile, which can be used by e.g. `exec` (and `login`), and produces output as seen below:
```shell
$ aws-vault exec Administrator-123456789012 -- aws sts get-caller-identity
Attempting to automatically open the SSO authorization page in your default
browser. If the browser does not open or you wish to use a different device to
authorize this request, …
```

Add support for AWS SSO profiles

---

USAGE.md
cli/add.go
vault/config.go
vault/config_test.go

Rename the `parent_profile` config variable to `include_profile` and expands the documentation.
Rationale: the relationship between profiles is not a parent-child relationship, it's a horizontal "mixin" import of config 
Fixes #520

Rename parent_profile to include_profile

---

USAGE.md

The format of the session duration isn't quite clear, but https://github.com/99designs/aws-vault/issues/544#issuecomment-607581197 explains it well. Adding it to the docs to make it clear for others.

Make session duration format clear in usage docs

---

contrib/completions/fish/aws-vault.fish

I figure this should make it easier for the maintainers to keep `fish` supported (via `aws-vault --completion-bash`), and I've found the `aws-vault exec ... --` completions invaluable day-to-day:

Improve fish shell completions

---

cli/exec.go
server/ec2.go
server/ecs.go

Hi aws-vault maintainers, thanks for this lovely tool and the excellent recent additions in the v6 beta! I've got a minor update here to use RFC3339 for all `time.Format()` calls related to credential expiration.
`exec` was using RFC3339 in some places but `"2006-01-02T15:04:05Z"` in others. The latter format renders:
```
2020-06-04T13:14:44-04:00
```
as:
```
2020-06-04T13:09:44Z
```
and leads to `Credentials were refreshed, but the refreshed credentials are still expired` errors as noted in #331. In the v6 beta I've seen those errors with both the credential helper and `--ecs-server` functionality.

Use RFC3339 consistently for expiration times

---

prompt/credui_windows.go
prompt/native_windows.go

This solved a pain point for me when using aws-vault on windows as a credential helper, since the console prompt doesn't work in that scenario. 
Forgive me, this is the first Go code that I've ever written. Hope it can be worked into something mergeable
Thanks

Add a prompt that is native to Windows

---

cli/add.go
prompt/terminal.go

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
This will prevent the secret output echoing back:
```
$ aws-vault add dev                                                                                 
Enter Access Key ID: BLABLA
Enter Secret Access Key: 🔒 
```
Fixes: https://github.com/99designs/aws-vault/issues/616

Read Secret Access Key with terminal.ReadPassword()

---

vault/oidctokenkeyring.go
vault/ssorolecredentialsprovider.go
vault/vault.go

Adds caching for OIDC tokens. As these tokens aren't attached to a profile, these will show up as "credentials" under `aws-vault list` for now.
@itsdalmo @rickardl could you please test this?
Fixes #571

Add OIDC token caching

---

vault/ssorolecredentialsprovider.go

I was testing the new OIDC caching in #628 (yay!) and ran into some errors when I had no existing OIDC entry in my keychain.
First, aws-vault would die immediately with:
```
aws-vault: error: exec: Failed to get credentials for <my-profile>: The specified item could not be found in the keyring
```
After a tweak to fix that, it would go through _most_ of the normal credential flow but die later:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45f99f8]
goroutine 6 [running]:
github.com/99designs/aws-vault/v6/vault.(*SSORoleCredentialsProvider).getRoleCredentials(0xc000314100, 0xc00014c000, 0x0, 0x0)
github.com/99designs/aws-vault/v6/vault/ssorolecredentialsprovider.go:58 +0xf8
...
```
After erroring …

Handle OIDC caching for new keyring entries

---

prompt/passotp.go

This pr adds support for using pass-otp as an otp prompt.
I am not sure if this would be better implemented as generic otp
prompt that can call any command to generate an otp code. That would
also be able to take the place of the ykman prompt. Either way,
given that pass is a supported backend, I think it makes sense to
support pass as an otp prompt as well.

Add pass-otp as an otp prompt

---

vault/oidctokenkeyring.go

I ran into the issue raised in #639 and went peeking at the cause. It looks like with `SessionKeyring`, expired keys get cleared out via `GarbageCollectOnce` at the beginning of keyring management calls. So callers get a not found error when trying to fetch non-existent _or_ expired creds.
This change tries to bring the same approach to OIDC tokens, so aws-vault will automatically try to create a new token in either case.
I'm not sure if this is the "right" way to handle the expired token case, but it's a conversation starter at least.

Return not found error for expired OIDC tokens

---

vault/cachedsessionprovider.go
vault/sessionkeyring.go

I'm fairly certain this is a bug, but could be specific to one of my use cases.  In this case I have a credential `42lines-vault` that is restricted by MFA.  I have a profile I assume `qa-assume` from the first credential.  The `qa-assume` credential is used by the metadata server.
When the ec2 metadata server refreshes the expired `qa-assume` credentials, there is no check to see if the cached `42lines-vault` credentials are expired;  `cachedsessionprovider.go` only checks for existence.
Logs which include call tracing I added.  (I have set the expiration time on the assume credential to 15 minutes to reduce the testing window, but this same behavior happens if the expiration is one hour.)  Note the expiration time of the cached credential:
`Re-using cached credentials …

Refresh cached credentials if already expired when calling Retrieve

---

USAGE.md
vault/vault.go

Add an environment variable `AWS_MIN_TTL` to set the expiry window for credentials, or in other words the minimum duration allowed for a credential

Add AWS_MIN_TTL to set expiry window

---

vault/config.go

Fixing a small pet peeve of mine, where I am still using `parent_profile` for IAM-configured profiles that haven't been converted to their SSO equivalents yet.
In v6.0.0, when using a profile that has a parent, the MFA prompt or first output of the command is written to the same line in my terminal, ex:
```
❯ aws-vault exec test -- terraform plan
Warning: parent_profile is deprecated, please use include_profile instead in your AWS configEnter token for arn:aws:iam::0123456789012:mfa/forename.surename: 000000
Refreshing Terraform state in-memory prior to plan...
```
This commit adds a new line so that the warning appears on it's own line:
```
❯ aws-vault exec test -- terraform plan
Warning: parent_profile is deprecated, please use include_profile instead in your AWS config
Enter token for …
```

newline added to end of parent_profile deprecation warning

---

cli/exec.go
iso8601/iso8601.go
iso8601/iso8601_test.go
server/ec2server.go
server/ecsserver.go

Add a function to format times with ISO 8601 format compatible with all AWS SDKs
Fixes #655

Add a function to format times compatible with aws sdks

---

contrib/scripts/aws-iam-create-yubikey-mfa.sh

Not all AWS User ARNs have the username as the second field. Some may
have it as the 3rd or 4th field. However, it seems very likely that most accounts
have them as the last field in the ARN.
This patch changes the behavior to grab the last field in the username and I hope
that it is behavior preserving for the original use case as well.
This patch is required for the organization that I work in and it would be great if we
can get this merged upstream!
Thanks for all the hard work that went into aws-vault. It's a great tool and I use
it everyday!

Handle additional username formats

---

contrib/scripts/aws-iam-create-yubikey-mfa.sh

If you run shellcheck on this script, you get the following error message:
In tpc/aws-yubikey-mfa/aws-iam-create-yubikey-mfa.sh line 6:
if [ -n "$AWS_SESSION_TOKEN" ]; then
^----------------^ SC2154: AWS_SESSION_TOKEN is referenced but not assigned.
Setting `-u` causes the script to exit if AWS_SESSION_TOKEN is unset. Reading from
an empty value will allow the script to proceed correctly, even if `-u` is set.
Thanks for all the hard work that went into aws-vault. It's a great tool and I use
it everyday!

Fixup shell-check error in Yubikey create script

---

USAGE.md
cli/rotate.go
vault/assumeroleprovider.go
vault/config.go
vault/config_test.go
vault/sessiontokenprovider.go
vault/vault.go

Support the `sts_regional_endpoints` in the aws config file or via the `AWS_STS_REGIONAL_ENDPOINTS` env var.
Reference: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#aws-sts
This may help with #543

Support sts_regional_endpoints configuration

---

README.md

The package has been included in the community repository, so there's no need to install it from AUR

Update arch linux install instructions

---

README.md

brew cask install aws-vault
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.

Change brew syntax to avoid a deprecation warning

---

USAGE.md
contrib/scripts/aws-iam-create-yubikey-mfa.sh
contrib/scripts/aws-iam-resync-yubikey-mfa.sh

This PR implements timed wait between code generation in aws mfa yubikey helper script `aws-iam-create-yubikey-mfa.sh`
as discussed here:
https://github.com/99designs/aws-vault/pull/559/files#r412054242
I also experienced some drifts in TOTP tokens - yubikey being out of sync with AWS and AWS not accepting codes. To address this issue and for convenient resync `aws-iam-resync-yubikey-mfa.sh` script was created.

added timed wait between code generations, added resync script

---

prompt/ykman.go

This change enables setting YKMAN_OATH_DEVICE_SERIAL to select a
particular Yubikey if more than one is attached to the device. It does
this by reading the serial from the env var, and adding the `--device
<serial>` to the `ykman` command.
Closes #638

Set YKMAN_OATH_DEVICE_SERIAL to select Yubikey

---

server/ec2alias_bsd.go

aws-vault is working on openbsd.

build for openbsd

---

contrib/scripts/aws-iam-create-yubikey-mfa.sh
contrib/scripts/aws-iam-resync-yubikey-mfa.sh

- removed bashisms from AWS helper scripts so they work under Linux / dash too
- forced (`-f`) `ykman` to overwrite MFA code on YubiKey if it exists already. this is useful when MFA config in AWS console has been deleted and setting up a new MFA using this script. `ykman` would otherwise fail silently and left AWS MFA in an inconsistent state (created but unactivated).
- fixed cleanup function to actually run on EXIT (`-z "$OUTFILE"` ?)
- removed `-u` (`nounset` ) to not fail with `unbound variable` if the script fails before setting `OUTFILE`

aws helper scripts fixed to work on more platforms

---

USAGE.md
vault/assumeroleprovider.go
vault/config.go
vault/config_test.go
vault/vault.go

This PR is trying to resolve #684 and implements the way to set Session Tags and Transitive Session Tags when `AssumeRole()` provider is used.
- Two new profile configuration parameters are introduced: `session_tags` and `transitive_session_tags`
- Two new environment variables are introduced: `AWS_SESSION_TAGS` and `AWS_TRANSITIVE_TAGS`
It is possible to configure each profile in the chain individually, as well as the target profile with environment variables.

STS AssumeRole Session Tags implementation

---

Makefile

Should fix https://github.com/99designs/aws-vault/issues/758, but comments definitely welcome from people with more understanding than me on Go cross-compilation and the build/release process for aws-vault (@mtibben!).
In order to try and validate this, I've compiled the native target on darwin/amd64 (Catalina 10.15.7) and  darwin/arm64 (Big Sur 11.2.3) and cross-compiled for the opposite architecture on both darwin/amd64 and darwin/arm64.
In all cases, I've run `aws-vault --debug` and checked for the presence of keychain in the list of backends.
Original commit message follows.
This is an attempt to fix a lack of keychain support in darwin/arm64
binaries that have been cross-compiled on other platforms as described
in https://github.com/99designs/aws-vault/issues/758 and hinted at in
the …

Set flags to cross-compile darwin/arm64 on darwin/amd64 and vice versa

---

cli/global.go

Given one can simply press <kbd>Return</kbd> when prompted for a password in the terminal, I think we could also allow `AWS_VAULT_FILE_PASSPHRASE` to be empty.
This changes `fileKeyringPassphrasePrompt` in order to allow empty passphrases by using [`LookupEnv`](https://golang.org/pkg/os/#LookupEnv) instead of [`Getenv`](https://golang.org/pkg/os/#Getenv)

Use LookupEnv rather than Getenv for AWS_VAULT_FILE_PASSPHRASE

---

README.md

The aws-vault software is packaged and built for OpenSUSE/SUSE, but the version update process is manual at the moment.  It would be fairly easy to set it to auto-build new versions, but that would require someone to enable a webhook on the repo which notifies the OpenBuildService when a new version is released.  I'd be happy to help set that up on the SUSE side if the repo owner is willing to add the hook and create an OBS account.  Otherwise, I suppose I could set up my own fork and add a scheduled action to sync mine from upstream.

Add OpenSUSE update instructions

---

prompt/osascript.go

Hi maintainers! I'm Josh and I work at Bison Trails. We're doing an internal hackathon this week.
Our team loves aws-vault, but it got flagged during a recent security review. Our team voted to use our hackathon time to patch vulnerabilities in our favorite OSS tools and specifically to try to get aws-vault approved for usage within our organization.
- Prevents AppleScript injections via the `~/.aws/config#serialMFA` configuration property 
These changes should improve aws-vault's security posture. We identified this vulnerability using [Salus](https://github.com/coinbase/salus) and the [OSSF scorecard](https://github.com/ossf/scorecard). The specific issues I am hoping to address here are:
- Preventing unintentional code execution by properly quoting and escaping the value for mfaSerial …

Prevent osascript prompt code injection

---

cli/exec.go
go.mod
prompt/kdialog.go
prompt/passotp.go
prompt/ykman.go
prompt/zenity.go
server/ec2alias_windows.go
server/ec2proxy_default.go
vault/assumerolewithwebidentityprovider.go

Hi maintainers! I'm Josh and I work at Bison Trails. We're doing an internal hackathon this week.
Our team loves aws-vault, but it got flagged during a recent security review. Our team voted to use our hackathon time to patch vulnerabilities in our favorite OSS tools and specifically to try to get aws-vault approved for usage within our organization.
- Prevent wrong executable for credential process and exec subcommand on windows by removing current working directory from the beginning of `$PATH`. see more here https://blog.golang.org/path-security
These changes should improve aws-vault's security posture. We identified this vulnerability using [Salus](https://github.com/coinbase/salus) and the [OSSF scorecard](https://github.com/ossf/scorecard). The specific issues I am hoping to address …

prevent windows exec unintentional relative pathing

---

USAGE.md

c.f. https://github.com/99designs/aws-vault/search?q=AWS_SESSION_TAGS

Fix incorrect environment variable name to override STS session tags

---

.github/dependabot.yml

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
Having knowledge about vulnerabilities of the dependencies helps the project owners decide on their dependencies security posture to make decisions.
If the project decides to get updates only on security updates and not on any version updates then setting these options would not open any PR 's open-pull-requests-limit: 0

Enable dependabot to get security updates 

---

USAGE.md
vault/assumeroleprovider.go
vault/config.go
vault/vault.go

Added support for specifying source identity when assuming roles. Can be specified with `source_identity` in config file or `AWS_SOURCE_IDENTITY` environment variable.
Fixes #771

Add support for source identity on sessions

---

cli/exec.go
vault/config.go
vault/ssorolecredentialsprovider.go
vault/vault.go

By default `aws-vault` opens the the AWS SSO link in the user's
default browser, but specifying `--no-browser` will only print
the AWS SSO link to the terminal, allowing the user to open
the link in a non-default way (eg firefox profile, on a different
machine, etc)
Fixes #678

Add `--stdout` option to `aws-vault exec`

---

USAGE.md
cli/exec.go
contrib/_aws-vault-proxy/Dockerfile
contrib/_aws-vault-proxy/docker-compose.yml
contrib/_aws-vault-proxy/go.mod
contrib/_aws-vault-proxy/go.sum
contrib/_aws-vault-proxy/main.go
go.mod
go.sum
server/ecsserver.go

Adds a new route to `aws-vault exec --ecs-server` to assume role credentials dynamically.
The ECS server now responds to requests on `/role-arn/YOUR_ROLE_ARN` with the role credentials, making it usable with the `AWS_CONTAINER_CREDENTIALS_FULL_URI` or `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment 
variables. These environment variables are used by the AWS SDKs as part of the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default).
The major use-case for this are applications that may wish to assume a role dynamically, without the role specified in the aws config file.
In particular, this is designed to allow aws-vault to run on your local host while docker images access role credentials dynamically. This …

Add a dynamic role route to ECS server

---

server/ec2server.go

A valid `Host` header may explicitly include the port, though it's optional for default ports ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)). Had this come up as an issue WRT integrating https://github.com/fog/fog-aws into an application, which makes requests to http://169.254.169.254:80 as opposed to http://169.254.169.254. This is technically not incorrect, so seemed better to open a PR here than there.

allow Host header with explicit :80 included

---

.github/workflows/go.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

USAGE.md
vault/config.go

AWS SSO was too easy to pronounce, so it's now AWS IAM IC. Update docs and code comments to match.
I have left https://github.com/99designs/aws-vault/blob/master/USAGE.md#aws-single-sign-on-aws-sso working so any that existing inbound hyperlinks don't break.

Update for rename of AWS SSO to “AWS IAM Identity Center”

---

USAGE.md

I have multiple Yubikeys plugged into my computer and I looked for the possibility to specify the `--device` flag to the `ykman` command. I found out this was already implemented in https://github.com/99designs/aws-vault/pull/748 though not added to the documentation, so this is what this PR does.

Add YKMAN_OATH_DEVICE_SERIAL to USAGE.md

---

USAGE.md

PR related to #1056
* Flag issue during 'Rotating credentials' section
* Expand 'Temporary credentials limitations with STS, IAM' with 1) error user will encounter, 2) mitigations 
* ?correct? possible existing type in 'MFA' section (however I'm unsure if the entire sentence is valid)

Improve signposting of IAM api call restrictions

---

cli/exec.go
go.mod
prompt/kdialog.go
prompt/passotp.go
prompt/ykman.go
prompt/zenity.go
server/ec2alias_windows.go
server/ec2proxy_default.go
vault/assumerolewithwebidentityprovider.go

As of Go 1.19, the changes in execabs have been incorporated into os/exec

Remove golang.org/x/sys/execabs

---

cli/login.go

Reverts 99designs/aws-vault#892 due to [regression](https://github.com/99designs/aws-vault/issues/1102#issuecomment-1378061497)

Revert "With login, `SSOUseStdout` should follow `--stdout`"

---

vault/config.go
vault/vault.go

Refactor `tempCredsCreator`, which was a particularly tricky part of the code to understand. This should make the logic much simpler to understand
on master:
```
$ gocyclo vault/vault.go
19 vault (*tempCredsCreator).provider vault/vault.go:204:1
```
on this branch:
```
$ gocyclo vault/vault.go
8 vault (*tempCredsCreator).GetProviderForProfile vault/vault.go:223:1
4 vault (*tempCredsCreator).getSourceCreds vault/vault.go:204:1
```

Simplify creation of temporary creds

---

.gitignore
USAGE.md
vault/config.go
vault/config_test.go
vault/vault.go

New AWS CLI changed config format for SSO values. Instead of specifying `sso_start_url` and `sso_region`,
it now makes `sso_session` profile param, that points to a separate `[sso-session]` section.
This PR adds support for the `sso_session` param and parsing `[sso-session]` section.

Handle [sso-session] section

---

USAGE.md
contrib/scripts/aws-iam-create-yubikey-mfa.sh
contrib/scripts/aws-iam-resync-yubikey-mfa.sh

See https://github.com/99designs/aws-vault/issues/1100
I've gotten AWS Vault to work using a Yubikey and a virtual TOTP device, using AWS' new feature for multiple MFA devices. I've updated the documentation to be consistent with this new capability, and have explained how to get both a Yubikey and a Virtual TOTP device working with the same IAM User.

Update Documentation to reflect new Multi-MFA per IAM User functionality on AWS.

---

USAGE.md
vault/assumerolewithwebidentityprovider.go
vault/config.go
vault/credentialprocessprovider.go
vault/credentialprocessprovider_test.go
vault/executeprocess.go
vault/vault.go

The AWS CLI supports calling an external credential provider via the `credential_process` configuration option.  However, as stated in the [AWS CLI Docs](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes):
> NOTE: Unlike with assume role credentials, the AWS CLI will NOT cache process credentials. If caching is needed, it must be implemented in the external process.
I have a use case where I must call an external process to obtain a credential.  I wish to cache this credential to avoid repeated API calls and 2FA prompts.  Rather than rolling my own caching, I would prefer to make use of `aws-vault` for this purpose.
This PR implements the equivalent `credential_process` logic in `aws-vault exec`.  I am aware of the existing use case …

Add support for consuming credential_process in 'aws-vault exec'.

---

vault/vault.go

aws cli doesn't allow roles in the profile when using `credential_process`, aws-vault should behave similarly

Fix credential_process 

---

README.md
cli/exec.go

Support `AWS_CREDENTIAL_EXPIRATION`, the new env var used by aws cli in https://github.com/aws/aws-cli/pull/7398
Fixes #1103

Add new expiration env var

---

vault/config.go

Remove support for parent_profile, deprecated in v5

Remove support for parent_profile, deprecated in v5

---

cli/exec.go
cli/export.go
main.go

The `exec --json` flag was always a bit weird, because the `--json` flag changes the behaviour and doesn't "exec" anything at all.
This remedies that weirdness by creating a `aws-vault export` command that exports credentials in a variety of formats.
- `aws-vault export --format=env PROFILE` prints in env-var format e.g. `FOO=BAR`
- `aws-vault export --format=export-env PROFILE` prints in env-var format with en export e.g. `export FOO=BAR`
- `aws-vault export --format=json PROFILE` prints in json format compatible with `credentials_process`
- `aws-vault export --format=ini PROFILE` prints in ini format compatible with `~/.aws/credentials`
The old `exec --json` flag still works but also prints out a deprecation notice to stderr

Add `aws-vault export` cmd

---

cli/exec.go

aws-vault has traditionally stuck to the unix philosophy of "silence is golden". However there are a number of scenarios which consistently confuse users.
1. When aws-vault defaults to using `SHELL` and creates a subshell when a command isn't provided
2. When the root password is prompted for when using `--ec2-server`
3. When the app doesn't support `AWS_CONTAINER_CREDENTIALS_FULL_URI` when using `--ecs-server`
For that reason, this PR changes aws-vault to provide minimalistic feedback to the user when these scenarios come up.

Provide feedback to user when prudent

---

USAGE.md
cli/exec.go

`--ec2-server` has many downsides compared to `--ecs-server`.
This changes `--server` to use the ECS server implementation rather than the EC2 server

Make --ecs-server the default server implementation

---

cli/exec.go
cli/export.go
cli/global.go
cli/login.go
cli/rotate.go

When `--prompt` is not specified, automatically select the best prompt driver to use. By default `terminal` will be selected, but an alternative will be chosen if `--ecs-server` or `--ec2-server` are being used 
Fixes #888

Automatically select the best prompt driver

---

README.md
cli/exec.go

Remove use of unnecessary env vars.
- `AWS_DEFAULT_REGION`: use `AWS_REGION` instead. `AWS_DEFAULT_REGION` set the "default" region, and is unnecessary
- `AWS_SECURITY_TOKEN`: use `AWS_SESSION_TOKEN` instead
- `AWS_SESSION_EXPIRATION`: use `AWS_CREDENTIAL_EXPIRATION` instead

Remove use of old env vars

---

cli/export.go

Add region to `aws-vault export` output

---

README.md
cli/exec.go
cli/export.go

It turns out boto3 (the python SDK) still uses `AWS_DEFAULT_REGION`.
This reverts the recent removal of this env var in #1143

Revert removal of AWS_DEFAULT_REGION

---

cli/exec.go
cli/export.go
cli/global.go
cli/login.go
cli/rotate.go
go.mod
go.sum

If a TTY is not detected, prefer to use a non-terminal prompt method
Fixes #1015

Fix prompts required in non-tty processes

---

README.md
cli/exec.go
cli/export.go
cli/global.go
cli/login.go
cli/rotate.go
vault/config.go

Adds an an env var `AWS_VAULT_DISABLE_HELP_MESSAGE` to disable terminal help messages.
Ended up requiring a bit of refactoring to make handling this consistent
Fixes #1156

Env var to disable help message

---

cli/exec.go

Always attempt the execve, and fall back to a subprocess if the OS doesn't support it

Support execve syscall on all OSs that can

---

cli/exec.go
server/ec2proxy.go
server/ec2server.go

Shut down the proxy when the aws-vault process ends.
Fixes #1133

Shut down ec2 proxy automatically

---

vault/config.go
vault/config_test.go

Profiles that specify web identity process or files require the role ARN to be set as well. Since the 7.0.0 release, this has been failing validation because it is now considered to have two sources of credentials. This fixes the validation to correctly consider this as a profile with one source credential.
Fixes #1177

Web identity profiles with role ARNs are valid

---

go.mod
go.sum
prompt/terminal.go

This implements the fix suggested by @ngyuki in https://github.com/99designs/aws-vault/issues/1054. When using `prompt=terminal` (which we use to support both Linux and Mac using the same workflow and config, without `osascript` involvement), we used to have a workaround in `.aws/config` that would redirect the terminal prompt to stdout in most cases by adding ` 2> $(tty)` to the end of the `aws-vault` `credential_process` call, like this:
```
credential_process=sh -c 'aws-vault --prompt terminal export base --duration 12h --format=json 2> $(tty)'
```
With this patch we can remove that redirect and the prompt always shows up, even when called through the SDK via `aws --profile somerole s3 ls`, for example. Also removes the creation of spurious files named `not a tty` when …

Fix hang on invisible tty when using 2FA where prompt=terminal in some edge cases

---

cli/global.go

This is related to the discussion in #1185.
It's a bit verbose / copy-pasta as I couldn't figure out a good way to pre-validate EnumVars before their own option validation kicks in.
Also, I'm a golang newb so I apologize for any stupid mistakes I need to clean up.

Add explicit removal notice + instructions for --prompt=pass

---

cli/login.go
vault/assumeroleprovider.go
vault/assumerolewithwebidentityprovider.go
vault/cachedsessionprovider.go
vault/credentialprocessprovider.go
vault/sessiontokenprovider.go
vault/ssorolecredentialsprovider.go
vault/vault.go

If credentials are sourced from the environment or credential_process, check the caller ID to see if the session is an assumed role, or create a federated login if master credentials are found.
Fixes #1191

Fix credential type detection for login

---

server/ec2server.go

I suspect this was just typo'd initially, and it breaks e.g. the java sdk.
On ec2, old:
```
[josh@i-0600ab71d7a519927 ~]$ curl -v 169.254.169.254/latest/meta-data/dynamic/instance-identity/document > /dev/null
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/dynamic/instance-identity/document HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Content-Length: 339
< Date: Mon, 15 May 2023 10:49:36 GMT
< Server: EC2ws
< Connection: close
< 
{ [339 bytes data]
```
New:
```
[josh@i-0600ab71d7a519927 ~]$ curl -v 169.254.169.254/latest/dynamic/instance-identity/document > /dev/null
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET …
```

fix region query endpoint

---

USAGE.md

A short addition to the usage documentation that describes how to use `mfa_process` in `.aws/config` to generate tokens using a YubiKey and `ykman`. This allows more of the configuration to live in `.aws/config` as opposed to supplying CLI arguments or setting environment variables.

Describe how to use mfa_process with YubiKey

---

USAGE.md

This document incorrectly suggests `sso_role_name` corresponds to an IAM role, when it actually corresponds to an IAM Identity Center permission group.

Update docs describing `sso_role_name` parameter
