99designs/aws-vault

command/remove.go
Remove sessions also when using `aws-vault rm`
=> Remove sessions when using rm

exec.go
https://github.com/boto/boto/issues/3298
=> Boto use AWS_SECURITY_TOKEN vs AWS_SESSION_TOKEN

login.go, main.go, provider.go
Also fixes a build error in `provider.go`.
/cc @lox
=> Add MFA token input support for login command

exec.go
=> Rely on ENV only for profile and config in subproc

add.go, provider.go, rm.go, sessions.go
This moves the logic for storing, fetching and deleting sessions in the keyring into a dedicated class.
=> Move session logic into KeyringSessions

sessions.go
This fixes a bug where a session without an MFA could be used for a role with an MFA requirement. It also cleans up a boundary case where shorter session time could be ignored if a cached session existed.
=> Add a hash to the session key, tied to duration and mfa

keyring/keychain.go
As of macOS Sierra, Keychain files are stored with the extension `.keychain-db` rather than `.keychain`. This is a quick kernel-version check so that we use the correct extension on the user's OS.
Doing the version check via the `kern.osrelease` sysctl call isn't the "most correct" thing to do on macOS. The options are:
* Use the objective-c `isOperatingSystemAtLeastVersion` function from the Foundation framework. This would need me to know how to allocate and fill a `NSOperatingSystemVersion` struct full of `NSNumber` fields, properly allocate those fields, and manually memory manage them, so after fumbling with it for a bit I went looking elsewhere
* Shell out to `sw_vers` 😐 
I'm happy enough with this sysctl version; it is reliable, just not "obvious" that kernel version 16.x.x is …
=> Use `.keychain-db` extension on macOS Sierra

.travis.yml, Makefile, add.go, config.go, exec.go, exec_test.go, keyring/array.go, keyring/array_test.go, login.go, ls.go, ls_test.go, main.go, provider.go, rm.go, rotate.go, server.go, sessions.go
This project is woefully short on tests and CI. This PR will add some basic tests and CI via Travis. Feels @joho @mtibben @pda?
=> Basic tests and Travis-CI integration

login.go
Currently trying to login with IAM credentials doesn't work, it fails with Bad Request. 
This uses GetFederationToken to make it work.
=> Allow console login for IAM Credentials without AssumeRole

README.md
I had to search the github issues to find this out.
=> Add a note on configuring Linux

keyring/keychain_test.go
Looks like I broke the build in #130. This fixes it.
=> Fix failing keychain tests

config.go, keyring/keychain.go, keyring/keychain_test.go, provider.go, sessions.go, vendor/vendor.json
#138 had some things in it that weren't related to the PR title and are important, so I am going to put them into their own PR's. 
Reverts 99designs/aws-vault#138
=> Revert "Fixed regression that prompted for keychain access for sessions"

keyring/keychain.go, keyring/keychain_test.go, vendor/vendor.json
One is for adding, one is for search. Before this change items were incorrectly added to the default keychain.
=> Use SetMatchSearchList vs UseKeychain

README.md
in response to the discussion in #164
=> add note about mfa_serial / assuming roles

cli/add.go, cli/login.go, cli/rotate.go, vault/rotator.go
This is why key rotation was failing, new IAM keys take a while to propagate. This adds a terrible sleep and then poll. 
Fixes #132.
=> IAM takes a while to propagate new keys

README.md
=> Adds documentation for removing sessions

vault/config.go, vault/config_test.go, vendor/github.com/go-ini/ini/LICENSE, vendor/github.com/go-ini/ini/Makefile, vendor/github.com/go-ini/ini/README.md, vendor/github.com/go-ini/ini/README_ZH.md, vendor/github.com/go-ini/ini/file.go, vendor/github.com/go-ini/ini/ini.go, vendor/github.com/go-ini/ini/key.go, vendor/github.com/go-ini/ini/parser.go, vendor/github.com/go-ini/ini/section.go, vendor/github.com/go-ini/ini/struct.go, vendor/vendor.json
Closes #187.
Thanks so much to @Unknwon for https://github.com/go-ini/ini/issues/131! 🙇🏼 🙌🏻 💪🏼
=> Bump go-ini version to supported "nested config"

.dockerignore, Dockerfile, docker-compose.yml
This adds a Dockerfile for testing the Linux bits easily. Also should close #192.
=> Add a dockerfile for linux testing

.travis.yml
See https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce
=> Route builds back to Xcode 7.3 image

cli/global.go, docker-compose.dev.yml, vendor/github.com/99designs/keyring/kwallet.go, vendor/github.com/99designs/keyring/libsecret.go, vendor/vendor.json
=> Fix nil pointer panic in keyring

vault/config.go
Hi! This will create a dir and config file if they don't exist already.
Related to: https://github.com/99designs/aws-vault/issues/175
Please let me know if any changes should be made. Thanks!
=> Refactor to create config file if one does not exist already.

README.md
Add a single-quote to make the word 'operating system' possessive. Thanks for this great tool!
=> Small typo in README.me

.travis.yml, vendor/github.com/keybase/go-keychain/corefoundation_1.10.go, vendor/github.com/keybase/go-keychain/corefoundation_pre1.10.go, vendor/github.com/keybase/go-keychain/keychain_1.10.go, vendor/github.com/keybase/go-keychain/keychain_pre1.10.go, vendor/github.com/keybase/go-keychain/macos_1.10.go, vendor/github.com/keybase/go-keychain/macos_pre1.10.go, vendor/vendor.json
Updates the keybase/go-keychain dependency for go 1.10 compatibility.
changelog: https://github.com/keybase/go-keychain/compare/e39a0e22a1cbdbbcdc24b8556df51019c30df068...70b98e9c8d754db775c5bd3b2de3670cc76f1825
=> Update go-keychain for go 1.10 compatibility

USAGE.md
Adds additional documentation on commands to USAGE.md
Pulls in #220 to explain --no-session
=> Additional documentation in USAGE.md

vault/provider.go, vault/rotator.go
Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>
Fixes #256 
@aboutte
=> Updating session creator to always use the region specified

.travis.yml, Makefile, vault/config.go, vault/provider.go
Also add a `go vet` and `gofmt` to Travis to catch style issues.
=> Update travis config and Makefile for go 1.11

vault/rotator.go
=> Best guess stab at IAM vs STS for Rotation

cli/login.go, cli/ls_test.go, vault/provider.go
This PR does the following:
- Fixes: https://github.com/99designs/aws-vault/issues/258
- Pulls in changes from: https://github.com/99designs/aws-vault/pull/259 and addressed the PR comments
- Pass the region to the client
- Fix a failing `go vet`
Special thanks to @sprice-janrain
Signed-off-by: Noel Georgi <git@frezbo.com>
=> login endpoints for region

prompt/osascript.go, prompt/zenity.go
Adds a zenity prompt driver for linux.
=> add zenity prompt driver

.gitignore, completions/bash/aws-vault, completions/zsh/_aws-vault
They are based on the shell completion scripts generated by kingpin in alecthomas/kingpin#252. Modified to complete commands after '--'.
Fixes #70
=> Add custom shell completion scripts

vault/rotator.go
=> Strip path from usernames found in error message.

cli/exec.go
=> Update to use UTC

cli/exec.go
=> use Expire() to set Expiration with --json flag

README.md
I realized I was missing documentation for #388 - Here's that missing information for the readme.
=> Added documentation around MFA Serial override

USAGE.md
=> Added documentation of pass env vars

README.md
- https://github.com/Homebrew/linuxbrew-core/pull/15023
=> README: The aws-vault install command for Homebrew on Linux has changed

cli/global.go
=> Make password prompts go to stderr

cli/exec.go, cli/login.go, go.mod, go.sum, vault/provider.go
Reverse #421 in favour of https://github.com/99designs/keyring/pull/53
=> Handle forward slash in pass

vault/provider.go
We now have a way to [globally set an MFA device with `AWS_MFA_SERIAL`](https://github.com/99designs/aws-vault/pull/443), so I believe we can now remove the `mfa_serial` chaining behaviour, restoring compatibility with aws-cli config
Fixes #438
=> Remove profile chaining for MFA to restore aws-cli compatibility

cli/rotate.go, vault/rotator.go, vault/tempcreds.go
Removed `--mfa-token`: There are 2 prompts for an MFA token during a rotate, so this part is always interactive. i.e it doesn't make much sense to collect 1 token but not the second
Removed `--no-session`: No session is now the default. A session is only used if using master creds and no role, and an MFA serial is specified
=> Refactor rotate and remove --mfa-token and --no-session flags

USAGE.md
This is a common issue for folks -- See issues: #534, #219, and #211. Hopefully this documentation helps others find this simple way to configure how often you need to supply your password.
=> Adds info on changing Keychain password timeout

main.go
This is a follow-up for my comment here: https://github.com/99designs/aws-vault/pull/433/files#issuecomment-617656861
/cc @mtibben / @pbitty
=> Stream errors to stderr

server/ec2.go
Fixes #578
With the aws-vault EC2 metadata service running, it's possible for an attacker controlling any web page the victim visits with javascript enabled to mount a [DNS rebinding attack](https://en.wikipedia.org/wiki/DNS_rebinding) to grab short-lived credentials from the aws-vault server.
This requires the http request Host to be 169.254.169.254 to mitigate the attack.
=> Check the host header to mitigate a DNS rebinding attack

server/ec2alias_windows.go
Pretty straightforward, hope it´s useful!
=> Add spanish language to error message checking

Makefile
Closes https://github.com/99designs/aws-vault/issues/750
=> Added darwin osx arm binaries for M1

cli/remove.go
Closes https://github.com/99designs/aws-vault/issues/730
=> Allow to force-remove a profile without a prompt

USAGE.md, contrib/scripts/aws-iam-create-yubikey-mfa.sh, contrib/scripts/aws-iam-resync-yubikey-mfa.sh, prompt/ykman.go
`oath add` and `oath code` are deprecated
=> Update commands to setup MFA

vault/ssorolecredentialsprovider.go
Occasionally AWS returns 401 unauthorized errors on `GetRoleCredentials` with OIDC tokens that shouldn't have expired yet according to the expiration date returned by AWS. The error message in these situations looks like this:
```
aws-vault: error: exec: Failed to get credentials for <redacted>: operation error SSO: GetRoleCredentials, https response error StatusCode: 401, RequestID: 10a9bfff-90f9-48f4-8ab7-<redacted>, UnauthorizedException: Session token not found or invalid
```
When this happened the only solution was to run `aws-vault clear`.
This error has occurred in the past when AWS returned the wrong expiration date for some time (https://github.com/99designs/aws-vault/issues/854 and https://github.com/99designs/aws-vault/issues/722) and it still happens occasionally to some …
=> Recreate OIDC token when 401 error is returned

cli/add.go, cli/clear.go, cli/exec.go, cli/global.go, cli/list.go, cli/login.go, cli/proxy.go, cli/remove.go, cli/rotate.go, go.mod, main.go, server/ec2server.go, server/ecsserver.go, vault/config_test.go, vault/sessionkeyring_test.go, vault/vault.go
=> Update go module to v7

cli/login.go
=> Support `login` from profile with `credential_process`

cli/exec.go, cli/export.go, cli/login.go, cli/rotate.go, vault/vault.go
=> Use DI for useSessionCache

go.mod, vault/assumeroleprovider.go, vault/mfa.go, vault/sessiontokenprovider.go
=> Remove reference to pointer

vault/vault.go, vault/vault_test.go
Prioritise the `source_profile` over sso config.
Fixes #1195
=> Prioritise source_profile over sso config
